# ZMQ properties
data_queue_port: 5551
controls_queue_port: 5552
# Constant properties
path_to_training: "../"
path_to_session_files: "../"
path_to_dagger_models: "../"

recording_height: 80
recording_width: 160
recording_fps: 20
frame_height: 50
frame_width: 160

# Procedural flags
control_mode: full_model # modes: full_model
model_start_mode: regular  # modes: regular
m_length: 1 # memory length
m_interval: 1 # memory interval

path_to_models: ""
# model_name: masked_0.128_0.176.h5
# model_name: new_0.13_0.21.h5
# model_name: model_n1_m1_13.h5
# model_name: model_team_3_1.h5
# model_name: model_team_3_20210115_182559_1epoch.h5
# model_name: model_team_3_20210115_184854_10epoch.h5
# model_name: model_team_3_20210116_235249_10epochs_ca1_ca2.h5
# model_name: model_team_3_20210117_002007_12epochs_ca1_ca2.h5
# model_name: model_team_3_20210117_012558_10epochs_ca1_ca2_ca3.h5
# model_name: model_team_3_20210117_021502_12epochs_ca1_ca2_ca3.h5 # 2nd BEST
# model_name: model_team_3_20210117_134237_10epochs_ca1_ca2_ca3_ca4.h5 # bagus untuk zig-zag
# model_name: model_team_3_20210117_145523_12epochs_ca1_ca2_ca3_ca4.h5 # BEST
# model_name: model_team_3_20210120_043317_25epochs_ca1_ca2_ca3_ca4.h5 # not good
# model_name: model_team_3_20210120_043328_50epochs_ca1_ca2_ca3_ca4.h5 # not good
model_name: model_team_3_20210120_213050_13epochs_ca1_ca2_ca3_ca4_ca5.h5

# Imitation learning
dagger_training_enabled: false
dagger_epoch_size: 1600
dagger_epochs_count: 12
