# ZMQ properties
data_queue_port: 5551
controls_queue_port: 5552
# Constant properties
path_to_training: "../test/"
path_to_session_files: "../test/"
path_to_dagger_models: "../test/"

recording_height: 80
recording_width: 160
recording_fps: 20
frame_height: 50
frame_width: 160

# Procedural flags
control_mode: full_model # modes: full_model
# control_mode: full_expert # modes: full_model
model_start_mode: regular  # modes: regular
m_length: 1 # memory length
m_interval: 1 # memory interval

path_to_models: ""
# model_name: masked_0.128_0.176.h5
# model_name: new_0.13_0.21.h5
model_name: src/new_0.13_0.21.h5
# model_name: model_n1_m1_13.h5

# Imitation learning
dagger_training_enabled: false
dagger_epoch_size: 1600
dagger_epochs_count: 12

# For RCSnail-Connector
window_width: 965
window_height: 485
FPS: 30
track: eeden
# car: eeden_i8_04
car: eeden_i8_05
# track: deltax
# car: deltax_i8_01
# Procedural flags
model_override_enabled: true
expert_supervision_enabled: true
